export const projects = [
  {
    id: 'project-1',
    slug: 'jaya',
    brand: 'Philippe Tullio',
    title: 'Jaya',
    category: 'Film',
    year: '2024',
  },
  {
    id: 'project-2',
    slug: 'project-2',
    brand: 'Cartier',
    title: "L'Odyssée",
    category: 'Film de marque',
    year: '2023',
    image: 'https://picsum.photos/id/1015/1920/1080',
    thumb: 'https://picsum.photos/id/1015/160/90',
  },
  {
    id: 'project-3',
    slug: 'project-3',
    brand: 'Angèle',
    title: "Bruxelles Je T'Aime",
    category: 'Clip',
    year: '2023',
    image: 'https://picsum.photos/id/1019/1920/1080',
    thumb: 'https://picsum.photos/id/1019/160/90',
  },
  {
    id: 'project-4',
    slug: 'project-4',
    brand: 'Canal+',
    title: 'La Saison',
    category: 'Fiction',
    year: '2022',
    image: 'https://picsum.photos/id/1022/1920/1080',
    thumb: 'https://picsum.photos/id/1022/160/90',
  },
  {
    id: 'project-5',
    slug: 'project-5',
    brand: 'Dior',
    title: 'Sauvage',
    category: 'Publicité',
    year: '2022',
    image: 'https://picsum.photos/id/1039/1920/1080',
    thumb: 'https://picsum.photos/id/1039/160/90',
  },
];
