export const projects = [
  {
    id: 'showreel',
    slug: 'showreel',
    videoUrl: 'https://www.youtube.com/watch?v=j5t18TrkiSE',
    brand: 'Philippe Tullio',
    title: { fr: 'Démo', en: 'Showreel' },
    category: { fr: 'Reel', en: 'Reel' },
    year: '2023',
    duration: '1 min 43',
    description: {
      fr: "Voici la présentation de mon travail de réalisateur. Films d'action, horreur, drame, satire.",
      en: "Here's the presentation of my work as a director. Action films, horror, drama, satire.",
    },
    credits: [{ role: 'direction', name: 'Philippe Tullio' }],
    enableCTA: false,
    ctaHref: '/about#showreel',
    noPage: true,
  },
  {
    id: 'crako',
    slug: 'crako',
    videoUrl: 'https://vimeo.com/722961162',
    brand: 'Philippe Tullio',
    title: { fr: 'Crako', en: 'Crako' },
    category: { fr: 'Action / Horror', en: 'Action / Horror' },
    year: '2022',
    duration: '1 min 45',
    description: {
      fr: "Après avoir braqué une banque, une équipe de sept mercenaires part se réfugier dans une ville abandonnée: CRAKO.\n\nCette ville est en fait le fief d'un baron de la drogue, Emilio. Lorsque ce dernier apprend que l'équipe du braquage se trouve dans sa ville, il décide de leur mener une guerre sans merci.\n\nPour avoir une chance de survivre, l'équipe va devoir courir et se battre contre une armée de CRAKOS alors qu'une série de pièges se referme sur eux…",
      en: "Ex commander of the special ops forces General Mike Ferguson and his team have just robbed a bank ranking a huge payday. As they're chased through the city by the police, they eventually outrun them and hide in an abandoned and mysterious town: CRAKO.\n\nNot long after, they discover that this town isn't abandoned. It is, in fact, infested with a new form of humanity, the Crakos, zombie-like human beings who have been genetically modified by flackbath, a drug invented by drug baron Mr. Wen.\n\nMike and his team must eliminate the Crakos one by one in order to survive and enjoy the spoils from their heist. But as the hunt begins, they are severely outnumbered…",
    },
    credits: [
      { role: 'direction', name: 'Philippe Tullio' },
      { role: 'screenplay', name: 'Philippe Tullio' },
      {
        role: 'cast',
        name: 'David Belle, Vincent Bouillion, Alex Lopoka, Diva Sicard, Dominique Lexilus',
      },
      { role: 'cinematography', name: 'Ali Lakrouf' },
    ],
  },
  {
    id: 'abaco',
    slug: 'abaco',
    brand: 'ABACO Paris',
    title: { fr: 'ABACO\nParis', en: 'ABACO\nParis' },
    category: { fr: 'Publicité', en: 'Commercial' },
    year: '2012',
    duration: '41 sec',
    description: {
      fr: "Crée dans les années 1987 la marque Abaco est aujourd'hui une marque reconnue pour la qualité de ses différentes peaux de cuir et de python.",
      en: 'Created in 1987, Abaco is now a brand recognized for the quality of its various leather and python skins.',
    },
    credits: [
      { role: 'direction', name: 'Philippe Tullio' },
      { role: 'production', name: 'Createams, Philippe Tullio' },
      { role: 'cast', name: 'Stéphane Ferrara' },
    ],
  },

  {
    id: 'jaya',
    slug: 'jaya',
    videoUrl: 'https://www.youtube.com/watch?v=tdYosTyxzw0&t=15s',
    brand: 'Philippe Tullio',
    title: { fr: 'Jaya', en: 'Jaya' },
    category: { fr: 'Action', en: 'Action' },
    year: '2015',
    duration: '6 min',
    description: {
      fr: "Semerkhet, un maître cruel et apparemment incontestable, règne en roi sur les Trois Royaumes. Mais lorsque son petit frère Jaya apprend que Semerkhet a forcé la princesse Cassiopée à se marier et qu'elle est toujours en vie, il se donne pour mission de s'échapper de la prison dans laquelle son frère l'a enfermé et de ramener l'équilibre dans les royaumes.",
      en: 'Semerkhet, a cruel and seemingly unchallengeable master, reigns as King over the Three Kingdoms. But when his little brother Jaya, learns that Semerkhet has forced princess Cassiopeia into marriage and that she is still alive, he makes it his mission to escape the prison his brother put him in and return balance to the kingdoms.',
    },
    credits: [
      { role: 'direction', name: 'Philippe Tullio' },
      { role: 'screenplay', name: 'Philippe Tullio, Jeremy Minui' },
      { role: 'cast', name: 'David Belle, Darren Shahlavi' },
      { role: 'cinematography', name: 'Ben Hardwicke' },
      { role: 'music', name: 'Ludovic Bource' },
    ],
  },
  {
    id: 'k-citizen',
    slug: 'k-citizen',
    videoUrl: 'https://youtu.be/GCaTRgUWj0c?si=tY5dbbd1ugEpELGN',
    brand: 'Philippe Tullio',
    title: { fr: 'K-Citizen', en: 'K-Citizen' },
    category: { fr: 'Drame', en: 'Drama' },
    year: '2010',
    duration: '29 min',
    description: {
      fr: "Charles Taylor, âgé de 65 ans, est l'un des hommes les plus riches et les plus puissants du monde aujourd'hui. Il est à la tête d'un empire médiatique, à travers lequel il contrôle et manipule des milliards d'esprits.\n\nUne nuit, il rencontre Mindy, âgée de 24 ans, qui bouleverse son monde. Sa relation avec l'homme le plus influent au monde pousse Charles dans le terrier du lapin, dans un voyage cathartique d'introspection profonde avec son moi plus jeune en 1969.\n\nIci, il découvre qu'il est un produit de son environnement, comme tout autre homme : un produit façonné par son père.\n\nSi vous aviez l'opportunité de retourner dans le temps, que vous diriez-vous ?",
      en: 'Charles Taylor, 65 years old, is one of the richest and most powerful men in the world today. He is at the head of a media empire, through which he controls and manipulates billions of minds.\n\nOne night, he meets Mindy, 24, who turns his world upside down. Her relationship with the most influential man alive, pushes Charles down the rabbit hole into a cathartic journey of deep introspection with his younger self in 1969.\n\nHere, he discovers that he is a product of his environment, like any other man: a product shaped by his father.\n\nIf you had the opportunity to go back in time, what would you say to yourself?',
    },
    credits: [
      { role: 'direction', name: 'Philippe Tullio, Stéphane Tullio' },
      { role: 'screenplay', name: 'Stéphane Tullio' },
      { role: 'cast', name: 'David A. Kimball, Kate French, James Horan' },
      { role: 'cinematography', name: 'Eli Smolkin' },
      { role: 'music', name: 'Brady Cohan' },
    ],
    festivals: [
      { name: 'Raindance Film Festival', year: '2010', src: '/raindance.jpeg' },
      {
        name: 'Festival de Cannes — Short Film Corner',
        year: '2010',
        src: '/SFC_blanc-1.png',
      },
      { name: 'Bel Air Film Festival', year: '2010', src: '/bel-air.png' },
    ],
  },
  {
    id: 'jesus-is-back',
    slug: 'jesus-is-back',
    videoUrl: 'https://youtu.be/LTgAH78aKxg?si=_aaYCDZ3ArGLppzo',
    brand: 'Philippe Tullio',
    title: { fr: 'Jesus Is\nBack', en: 'Jesus Is\nBack' },
    category: { fr: 'Comédie satirique', en: 'Satirical Comedy' },
    year: '2013',
    duration: '11 min',
    description: {
      fr: "Jésus est de retour et il est en colère. Deux mille ans ont passé depuis sa première visite et l'humanité n'a rien appris de ses enseignements et de son sacrifice. Plus personne ne craint pour son âme. L'homme se comporte comme s'il était le seul sur terre et agit comme si la terre avait été créée pour lui.\n\nSept hommes ont été convoqués pour répondre de l'humanité. Trouveront-ils l'absolution ?",
      en: "Jesus is back and he's angry. Two thousand years have passed since his first visit and human kind has learned nothing from his teachings and sacrifice. No one fears for their soul anymore. Man behave as if he is the only one on earth and acts as though earth was created for him.\n\nSeven men have been summoned to answer for mankind. Will they find absolution?",
    },
    credits: [
      { role: 'direction', name: 'Philippe Tullio, Stéphane Tullio' },
      { role: 'screenplay', name: 'Philippe Tullio, Stéphane Tullio' },
      { role: 'cast', name: 'John Fortson, Josiah D. Lee, Ayman Samman' },
      { role: 'cinematography', name: 'Eli Smolkin' },
      { role: 'music', name: 'Charles Edouards' },
    ],
  },
];
