export const projects = [
  {
    id: 'project-1',
    slug: 'jaya',
    brand: 'Philippe Tullio',
    title: 'Jaya',
    category: 'Film',
    year: '2015',
    duration: '6 min',
    description: {
      fr: "Semerkhet, un maître cruel et apparemment incontestable, règne en roi sur les Trois Royaumes. Mais lorsque son petit frère Jaya apprend que Semerkhet a forcé la princesse Cassiopée à se marier et qu'elle est toujours en vie, il se donne pour mission de s'échapper de la prison dans laquelle son frère l'a enfermé et de ramener l'équilibre dans les royaumes.",
      en: "Semerkhet, a cruel and seemingly unchallengeable master, reigns as King over the Three Kingdoms. But when his little brother Jaya learns that Semerkhet has forced princess Cassiopeia into marriage and that she is still alive, he makes it his mission to escape the prison his brother put him in and return balance to the kingdoms.",
    },
    credits: [
      { role: 'Réalisation', name: 'Tullio Philippe' },
      { role: 'Scénario', name: 'Tullio Philippe, Jérémy Minui' },
      { role: 'Casting', name: 'David Belle, Darren Shahlavi, Sarah Alami' },
      { role: 'Image', name: 'Ben Hardwicke' },
      { role: 'Musique', name: 'Ludovic Bource' },
    ],
  },
  {
    id: 'project-2',
    slug: 'project-2',
    brand: 'Cartier',
    title: "L'Odyssée",
    category: 'Film de marque',
    year: '2023',
    image: 'https://picsum.photos/id/1015/1920/1080',
    thumb: 'https://picsum.photos/id/1015/160/90',
  },
  {
    id: 'project-3',
    slug: 'project-3',
    brand: 'Angèle',
    title: "Bruxelles Je T'Aime",
    category: 'Clip',
    year: '2023',
    image: 'https://picsum.photos/id/1019/1920/1080',
    thumb: 'https://picsum.photos/id/1019/160/90',
  },
  {
    id: 'project-4',
    slug: 'project-4',
    brand: 'Canal+',
    title: 'La Saison',
    category: 'Fiction',
    year: '2022',
    image: 'https://picsum.photos/id/1022/1920/1080',
    thumb: 'https://picsum.photos/id/1022/160/90',
  },
  {
    id: 'project-5',
    slug: 'project-5',
    brand: 'Dior',
    title: 'Sauvage',
    category: 'Publicité',
    year: '2022',
    image: 'https://picsum.photos/id/1039/1920/1080',
    thumb: 'https://picsum.photos/id/1039/160/90',
  },
];
